# Feature Engineering
Feature Engineering is the process of converting raw data into meaningful numerical features so that a machine learning model can understand patterns and make better prediction

### 1. Feature explortion
The Process of analyzing and visualizing features to uncover patterns, distributions, correlations, and Pottential Issues in the data set before applying Machine Learning.

### 2. Feature Creation
The Procress of generating new meaningful features from existing data using domain Knowledge features from existing data using domain knowledge or mathematical operations to help the model learn better patterns.

### 3. Feature Encoding
The Process of converting Categorical or non-numeric features into numeric form so machine learning models can process them effectively.

### 4. Feature Scaling
The process of transforming numerical features to a standard range or distribution so that no feature dominates the learning process due to its scale.

### 5. Feature Selection
The process of identifying and keeping only the most relevent features while removing irrelevent or redundant ones to improve model performance and reduce overfitting.

## Feature Creation (Adds Intelligence)

#### Definiton :
Feature Creation is the process of creating new features from existing data using domian knowledge and mathematical operations to help the model learn better pattern.

#### Why it "Adds Intelligence" :
* Raw data may not show hidden relationships.
* New features provide extra information.
* Models cannot think logically guide learning.

#### Common Types of Feature Creation
* Domain-based fetaures (real-world logic)
* Mathematical combination (sum, average, ratio)
* Interaction features (combined effect of features)
* Polynomial features (non-linear relationships)

#### Example :
* Total_Marks = Math + Science
* Efficiency = Total_Marks / Study_Hours

### Impact on Model
- Improves accuracy
- Helps models capture complex patterns
- Makes simple models perform better

In [1]:
# Feature Creation
import pandas as pd

df = pd.DataFrame({
    "Study_Hours": [2, 4, 6, 8, 10],
    "Attendance": [60, 70, 80, 90, 95],
    "Maths": [46, 55, 65, 75, 80],
    "Science": [42, 58, 68, 78, 88]
})
df

   Study_Hours  Attendance  Maths  Science
0            2          60     46       42
1            4          70     55       58
2            6          80     65       68
3            8          90     75       78
4           10          95     80       88

In [2]:
# Domain-Based Feature
df["Total_Marks"] = df["Maths"] + df["Science"]
df

   Study_Hours  Attendance  Maths  Science  Total_Marks
0            2          60     46       42           88
1            4          70     55       58          113
2            6          80     65       68          133
3            8          90     75       78          153
4           10          95     80       88          168

In [3]:
# Mathematical Feature
df["Marks_per_Hour"] = df["Total_Marks"] / df["Study_Hours"]
df

   Study_Hours  Attendance  Maths  Science  Total_Marks  Marks_per_Hour
0            2          60     46       42           88       44.000000
1            4          70     55       58          113       28.250000
2            6          80     65       68          133       22.166667
3            8          90     75       78          153       19.125000
4           10          95     80       88          168       16.800000

In [4]:
# Interaction Featyre
df["Study_Attendence_Interaction"] = df["Study_Hours"] * df["Attendance"]
df

,Study_Hours,Attendance,Maths,Science,Total_Marks,Marks_per_Hour,Study_Attendence_Interaction
0,2,60,46,42,88,44.000000,120
1,4,70,55,58,113,28.250000,280
2,6,80,65,68,133,22.166667,480
3,8,90,75,78,153,19.125000,720
4,10,95,80,88,168,16.800000,950

In [5]:
# Ploynomial Feature
df["Study_Hours_Squared"] = df["Study_Hours"] ** 2
df

,Study_Hours,Attendance,Maths,Science,Total_Marks,Marks_per_Hour,Study_Attendence_Interaction,Study_Hours_Squared
0,2,60,46,42,88,44.000000,120,4
1,4,70,55,58,113,28.250000,280,16
2,6,80,65,68,133,22.166667,480,36
3,8,90,75,78,153,19.125000,720,64
4,10,95,80,88,168,16.800000,950,100

 ##  Feature Selection (Removes Noise)
 Feature selection is the process of selecting only relevent features and removing irrelevent or redundant ones to improve the model perfprmance.

 #### Why it "Removes Noise" :
 - Too many features confuse the model
 - Irrelevant features cause overfitting
 - Noise reduces prediction accuracy

#### Types of Feature Selection :
- Filter methods (correlation, chi-square)
- Wrapper methods (forward, backward, RFE)
- Embedded methods (Lasso, tree-based models)

#### Example :
- Removing weakly correlated features
- Dropping features with zero importance
- Selecting top features using RFE

Impact on Model :
- Reduces overfitting
- Improves generalization
- Speeds up training

In [6]:
df

,Study_Hours,Attendance,Maths,Science,Total_Marks,Marks_per_Hour,Study_Attendence_Interaction,Study_Hours_Squared
0,2,60,46,42,88,44.000000,120,4
1,4,70,55,58,113,28.250000,280,16
2,6,80,65,68,133,22.166667,480,36
3,8,90,75,78,153,19.125000,720,64
4,10,95,80,88,168,16.800000,950,100

In [7]:
X = df.drop("Science", axis=1)
y = df["Science"]

In [8]:
X

,Study_Hours,Attendance,Maths,Total_Marks,Marks_per_Hour,Study_Attendence_Interaction,Study_Hours_Squared
0,2,60,46,88,44.000000,120,4
1,4,70,55,113,28.250000,280,16
2,6,80,65,133,22.166667,480,36
3,8,90,75,153,19.125000,720,64
4,10,95,80,168,16.800000,950,100

In [9]:
y

0    42
1    58
2    68
3    78
4    88
Name: Science, dtype: int64

# FILTER METHODS (Statistics-Based)
### 🔷 Correlation Method

In [10]:
df.corr()["Science"].sort_values(ascending=False)

Science                         1.000000
Total_Marks                     0.998562
Study_Hours                     0.994309
Attendance                      0.994110
Maths                           0.992572
Study_Attendence_Interaction    0.983804
Study_Hours_Squared             0.958102
Marks_per_Hour                 -0.956224
Name: Science, dtype: float64

In [11]:
# Selecting Important Features
corr = df.corr()["Science"].abs()
corr

Study_Hours                     0.994309
Attendance                      0.994110
Maths                           0.992572
Science                         1.000000
Total_Marks                     0.998562
Marks_per_Hour                  0.956224
Study_Attendence_Interaction    0.983804
Study_Hours_Squared             0.958102
Name: Science, dtype: float64

In [13]:
selected_features = corr[corr > 0.8].index
selected_features

Index(['Study_Hours', 'Attendance', 'Maths', 'Science', 'Total_Marks',
       'Marks_per_Hour', 'Study_Attendence_Interaction',
       'Study_Hours_Squared'],
      dtype='object')