# Missing Values

In [14]:
import pandas as pd
df=pd.read_csv('weather.csv')
df

          City  Temperature  Humidity
0     Hyderbad         30.0       NaN
1     Hyderbad         35.0      40.0
2     Hyderbad          NaN      67.0
3     Hyderbad         45.0      58.0
4     Hyderbad         42.0       NaN
5   Vijayawada          NaN      86.0
6   Vijayawada         47.0      57.0
7   Vijayawada          NaN      74.0
8   Vijayawada         36.0       NaN
9   Vijayawada         47.0      95.0
10    Banglore         29.0      65.0
11    Banglore         37.0       NaN
12    Banglore          NaN      67.0
13    Banglore         28.0      85.0

In [15]:
df.isnull()

     City  Temperature  Humidity
0   False        False      True
1   False        False     False
2   False         True     False
3   False        False     False
4   False        False      True
5   False         True     False
6   False        False     False
7   False         True     False
8   False        False      True
9   False        False     False
10  False        False     False
11  False        False      True
12  False         True     False
13  False        False     False

In [16]:
df.isnull().sum()

City           0
Temperature    4
Humidity       4
dtype: int64

In [17]:
df_clean=df.dropna()
df_clean

          City  Temperature  Humidity
1     Hyderbad         35.0      40.0
3     Hyderbad         45.0      58.0
6   Vijayawada         47.0      57.0
9   Vijayawada         47.0      95.0
10    Banglore         29.0      65.0
13    Banglore         28.0      85.0

In [18]:
df

          City  Temperature  Humidity
0     Hyderbad         30.0       NaN
1     Hyderbad         35.0      40.0
2     Hyderbad          NaN      67.0
3     Hyderbad         45.0      58.0
4     Hyderbad         42.0       NaN
5   Vijayawada          NaN      86.0
6   Vijayawada         47.0      57.0
7   Vijayawada          NaN      74.0
8   Vijayawada         36.0       NaN
9   Vijayawada         47.0      95.0
10    Banglore         29.0      65.0
11    Banglore         37.0       NaN
12    Banglore          NaN      67.0
13    Banglore         28.0      85.0

In [20]:
df["Humidity"]=df["Humidity"].fillna(df.Humidity.mean())
df

          City  Temperature  Humidity
0     Hyderbad         30.0      69.4
1     Hyderbad         35.0      40.0
2     Hyderbad          NaN      67.0
3     Hyderbad         45.0      58.0
4     Hyderbad         42.0      69.4
5   Vijayawada          NaN      86.0
6   Vijayawada         47.0      57.0
7   Vijayawada          NaN      74.0
8   Vijayawada         36.0      69.4
9   Vijayawada         47.0      95.0
10    Banglore         29.0      65.0
11    Banglore         37.0      69.4
12    Banglore          NaN      67.0
13    Banglore         28.0      85.0

In [22]:
df["Temperature"]=df["Temperature"].fillna(df.Temperature.mean())
df

          City  Temperature  Humidity
0     Hyderbad         30.0      69.4
1     Hyderbad         35.0      40.0
2     Hyderbad         69.4      67.0
3     Hyderbad         45.0      58.0
4     Hyderbad         42.0      69.4
5   Vijayawada         69.4      86.0
6   Vijayawada         47.0      57.0
7   Vijayawada         69.4      74.0
8   Vijayawada         36.0      69.4
9   Vijayawada         47.0      95.0
10    Banglore         29.0      65.0
11    Banglore         37.0      69.4
12    Banglore         69.4      67.0
13    Banglore         28.0      85.0