# 1. What is Pandas?

# Pandas is a python lybrary used for data cleaning, analysis and manipulation.
# works like excel but faster.
# helps load, clean, filter, & analysis data.

# 2. Import Pandas

In [10]:
import pandas as pd
import numpy as np
pd.__version__  #it says pandas version

'2.2.3'

# 3. Pandas Data Structures

# series--- one dimentional column
# DataFrame--- Table with rows + columns

In [2]:
s=pd.Series([10,20,30])
s

0    10
1    20
2    30
dtype: int64

In [4]:
df=pd.DataFrame({
    "name":["sai","ajay","karthik"],
    "age":[18,19,20]
})
df

      name  age
0      sai   18
1     ajay   19
2  karthik   20

# 4. Reading Data(CSV)

In [40]:
df=pd.read_csv('weather_data.csv')
df

   Condition Play        City  Temperature  Humidity        Date
0      Rainy  Yes    Hyderbad           30        60  03-01-2025
1      Sunny  Yes    Hyderbad           35        40  06-01-2025
2   Overcast  Yes    Hyderbad           25        67  14-01-2025
3   Overcast  Yes    Hyderbad           45        58  24-01-2025
4      Sunny   No    Hyderbad           42        48  25-01-2025
5      Rainy  Yes  Vijayawada           30        86  03-02-2025
6      Sunny  Yes  Vijayawada           47        57  07-02-2025
7   Overcast  Yes  Vijayawada           26        74  12-02-2025
8      Rainy   No  Vijayawada           36        36  15-02-2025
9      Sunny   No  Vijayawada           47        95  22-02-2025
10     Sunny  Yes    Banglore           29        65  27-02-2025
11     Rainy   No    Banglore           37        57  03-03-2025
12  Overcast  Yes    Banglore           39        67  25-03-2025
13  Overcast  Yes    Banglore           28        85  29-03-2025

In [41]:
df.head()

  Condition Play      City  Temperature  Humidity        Date
0     Rainy  Yes  Hyderbad           30        60  03-01-2025
1     Sunny  Yes  Hyderbad           35        40  06-01-2025
2  Overcast  Yes  Hyderbad           25        67  14-01-2025
3  Overcast  Yes  Hyderbad           45        58  24-01-2025
4     Sunny   No  Hyderbad           42        48  25-01-2025

In [42]:
df.tail()

   Condition Play        City  Temperature  Humidity        Date
9      Sunny   No  Vijayawada           47        95  22-02-2025
10     Sunny  Yes    Banglore           29        65  27-02-2025
11     Rainy   No    Banglore           37        57  03-03-2025
12  Overcast  Yes    Banglore           39        67  25-03-2025
13  Overcast  Yes    Banglore           28        85  29-03-2025

In [43]:
df.info

<bound method DataFrame.info of    Condition Play        City  Temperature  Humidity        Date
0      Rainy  Yes    Hyderbad           30        60  03-01-2025
1      Sunny  Yes    Hyderbad           35        40  06-01-2025
2   Overcast  Yes    Hyderbad           25        67  14-01-2025
3   Overcast  Yes    Hyderbad           45        58  24-01-2025
4      Sunny   No    Hyderbad           42        48  25-01-2025
5      Rainy  Yes  Vijayawada           30        86  03-02-2025
6      Sunny  Yes  Vijayawada           47        57  07-02-2025
7   Overcast  Yes  Vijayawada           26        74  12-02-2025
8      Rainy   No  Vijayawada           36        36  15-02-2025
9      Sunny   No  Vijayawada           47        95  22-02-2025
10     Sunny  Yes    Banglore           29        65  27-02-2025
11     Rainy   No    Banglore           37        57  03-03-2025
12  Overcast  Yes    Banglore           39        67  25-03-2025
13  Overcast  Yes    Banglore           28        85  29-03-2025>

In [52]:
df.to_csv('weather_data.csv',index=False)

In [53]:
df.Date

0     03-01-2025
1     06-01-2025
2     14-01-2025
3     24-01-2025
4     25-01-2025
5     03-02-2025
6     07-02-2025
7     12-02-2025
8     15-02-2025
9     22-02-2025
10    27-02-2025
11    03-03-2025
12    25-03-2025
13    29-03-2025
Name: Date, dtype: object

# Missing Values

In [55]:
df.isnull()

    Condition   Play   City  Temperature  Humidity   Date
0       False  False  False        False     False  False
1       False  False  False        False     False  False
2       False  False  False        False     False  False
3       False  False  False        False     False  False
4       False  False  False        False     False  False
5       False  False  False        False     False  False
6       False  False  False        False     False  False
7       False  False  False        False     False  False
8       False  False  False        False     False  False
9       False  False  False        False     False  False
10      False  False  False        False     False  False
11      False  False  False        False     False  False
12      False  False  False        False     False  False
13      False  False  False        False     False  False

In [56]:
df=pd.DataFrame({
    "name":["sai","ajay","sai"],
    "age":[18,19,18]
})
df

   name  age
0   sai   18
1  ajay   19
2   sai   18

In [57]:
df.duplicated()

0    False
1    False
2     True
dtype: bool

In [58]:
df[df.duplicated()]

  name  age
2  sai   18

In [59]:
df=df.drop_duplicates()
df

   name  age
0   sai   18
1  ajay   19

int fact(int n)
{ 
    if(n==0)
{  
    return 1;
}
         return n*fact(n-1);
}
fact(5)

In [4]:
import pandas as pd
df=pd.read_csv('weather_data.csv')
df

   Condition Play        City  Temperature  Humidity        Date
0      Rainy  Yes    Hyderbad           30        60  03-01-2025
1      Sunny  Yes    Hyderbad           35        40  06-01-2025
2   Overcast  Yes    Hyderbad           25        67  14-01-2025
3   Overcast  Yes    Hyderbad           45        58  24-01-2025
4      Sunny   No    Hyderbad           42        48  25-01-2025
5      Rainy  Yes  Vijayawada           30        86  03-02-2025
6      Sunny  Yes  Vijayawada           47        57  07-02-2025
7   Overcast  Yes  Vijayawada           26        74  12-02-2025
8      Rainy   No  Vijayawada           36        36  15-02-2025
9      Sunny   No  Vijayawada           47        95  22-02-2025
10     Sunny  Yes    Banglore           29        65  27-02-2025
11     Rainy   No    Banglore           37        57  03-03-2025
12  Overcast  Yes    Banglore           39        67  25-03-2025
13  Overcast  Yes    Banglore           28        85  29-03-2025

In [5]:
df['Temperature'].max()

47

In [6]:
df['Temperature'].min()

25

In [7]:
df['Temperature'].mean()

np.float64(35.42857142857143)

In [8]:
df['Temperature'].describe()

count    14.000000
mean     35.428571
std       7.703289
min      25.000000
25%      29.250000
50%      35.500000
75%      41.250000
max      47.000000
Name: Temperature, dtype: float64

In [9]:
df[df.Temperature==df.Temperature.max()]

  Condition Play        City  Temperature  Humidity        Date
6     Sunny  Yes  Vijayawada           47        57  07-02-2025
9     Sunny   No  Vijayawada           47        95  22-02-2025

In [14]:
df.City[df.Temperature==df.Temperature.max()]

6    Vijayawada
9    Vijayawada
Name: City, dtype: object

In [16]:
df.count()

Condition      14
Play           14
City           14
Temperature    14
Humidity       14
Date           14
dtype: int64